version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v24.1
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: unless-stopped
    volumes:
      - data:/var/lib/cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5

  nakama:
    image: nakama-plus:latest
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama-plus migrate up --database.address root@cockroachdb:26257 &&
          exec /nakama/nakama-plus 
          --name nakama-single 
          --database.address root@cockroachdb:26257 
          --logger.level INFO 
          --session.token_expiry_sec 7200 
          --metrics.prometheus_port 9100 
          --runtime.path /nakama/data/modules
    restart: unless-stopped
    depends_on:
      cockroachdb:
        condition: service_healthy
    volumes:
      - nakama-data:/nakama/data
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama-plus", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']

        - job_name: nakama
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - '9090:9090'
    depends_on:
      - nakama

volumes:
  data:
  nakama-data: